/** @type {import('tailwindcss').Config} */
/**
 * Maps AskMcNeese design tokens from `src/styles/variables.css`.
 * variables.css is the source of truth — keep this file in sync when tokens change.
 * Dark theme: `.dark` block exists in variables.css; enable by adding class `dark` on a root.
 */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx,md,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          950: "var(--brand-950)",
          900: "var(--brand-900)",
          800: "var(--brand-800)",
          700: "var(--brand-700)",
          600: "var(--brand-600)",
          100: "var(--brand-100)",
          50: "var(--brand-50)",
        },
        accent: {
          gold: "var(--accent-gold)",
          "gold-hover": "var(--accent-gold-hover)",
          "gold-soft": "var(--accent-gold-soft)",
          "gold-text": "var(--accent-gold-text)",
        },
        "on-gold": "var(--text-on-gold)",
        canvas: "var(--canvas)",
        "canvas-elevated": "var(--canvas-elevated)",
        surface: "var(--surface)",
        "surface-subtle": "var(--surface-subtle)",
        "surface-hover": "var(--surface-hover)",
        "surface-selected": "var(--surface-selected)",
        "surface-brand-subtle": "var(--surface-brand-subtle)",
        "surface-accent-subtle": "var(--surface-accent-subtle)",
        action: {
          primary: "var(--action-primary)",
          "primary-hover": "var(--action-primary-hover)",
          "primary-pressed": "var(--action-primary-pressed)",
          "primary-text": "var(--action-primary-text)",
          "secondary-bg": "var(--action-secondary-bg)",
          "secondary-hover": "var(--action-secondary-hover)",
          "secondary-border": "var(--action-secondary-border)",
          "secondary-text": "var(--action-secondary-text)",
          "accent-bg": "var(--action-accent-bg)",
          "accent-hover": "var(--action-accent-hover)",
          "accent-text": "var(--action-accent-text)",
        },
        mcneese: {
          blue: "var(--brand-800)",
          gold: "var(--accent-gold)",
          dark: "var(--brand-900)",
          light: "var(--brand-600)",
          yellow: "var(--mcneese-yellow)",
          "on-yellow": "var(--mcneese-on-yellow)",
        },
        "mcneese-yellow": "var(--mcneese-yellow)",
        "mcneese-on-yellow": "var(--mcneese-on-yellow)",
        /* Compatibility aliases — prefer canvas / surface / surface-subtle / surface-hover */
        "surface-raised": "var(--surface)",
        "surface-sunken": "var(--surface-subtle)",
        background: "var(--canvas)",
        "bg-secondary": "var(--surface-subtle)",
        "bg-tertiary": "var(--surface-hover)",
        elevated: "var(--surface)",
        border: "var(--border-default)",
        "border-strong": "var(--border-strong)",
        "border-subtle": "var(--border-subtle)",
        "border-interactive": "var(--border-interactive)",
        "border-active": "var(--border-active)",
        "border-focus": "var(--focus-ring)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "text-disabled": "var(--text-disabled)",
        "text-inverse": "var(--text-inverse)",
        "text-link": "var(--text-link)",
        "text-link-hover": "var(--text-link-hover)",
        "primary-subtle": "var(--brand-100)",
        "accent-subtle": "var(--accent-gold-soft)",
        success: "var(--success)",
        "success-soft": "var(--success-soft)",
        warning: "var(--warning)",
        "warning-soft": "var(--warning-soft)",
        danger: "var(--danger)",
        "danger-soft": "var(--danger-soft)",
        /* Compat: existing components use text-error / bg-error */
        error: "var(--danger)",
        "error-soft": "var(--danger-soft)",
        info: "var(--info)",
        "info-soft": "var(--info-soft)",
        focus: "var(--focus-ring)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        xs: ["var(--text-xs)", { lineHeight: "var(--leading-normal)" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--leading-normal)" }],
        base: ["var(--text-base)", { lineHeight: "var(--leading-normal)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--leading-snug)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--leading-snug)" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "var(--leading-tight)" }],
        "3xl": ["var(--text-3xl)", { lineHeight: "var(--leading-tight)" }],
      },
      lineHeight: {
        tight: "var(--leading-tight)",
        snug: "var(--leading-snug)",
        normal: "var(--leading-normal)",
        relaxed: "var(--leading-relaxed)",
        prose: "var(--leading-prose)",
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        soft: "var(--shadow-sm)",
        card: "var(--shadow-md)",
        float: "var(--shadow-lg)",
        focus: "var(--shadow-focus)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        bubble: "18px",
        "bubble-tail": "4px",
      },
      height: {
        header: "var(--header-height)",
        "screen-safe": "100dvh",
      },
      minHeight: {
        composer: "var(--composer-min-height)",
      },
      width: {
        sidebar: "var(--sidebar-width)",
        "sidebar-collapsed": "var(--sidebar-collapsed-width)",
        "nav-rail": "var(--nav-rail-width)",
      },
      maxWidth: {
        chat: "var(--chat-max-width)",
        message: "var(--user-message-max-width)",
      },
      spacing: {
        1: "var(--space-1)",
        2: "var(--space-2)",
        3: "var(--space-3)",
        4: "var(--space-4)",
        5: "var(--space-5)",
        6: "var(--space-6)",
        8: "var(--space-8)",
        10: "var(--space-10)",
        12: "var(--space-12)",
        16: "var(--space-16)",
        20: "var(--space-20)",
        24: "var(--space-24)",
        "safe-top": "env(safe-area-inset-top, 0px)",
        "safe-right": "env(safe-area-inset-right, 0px)",
        "safe-bottom": "env(safe-area-inset-bottom, 0px)",
        "safe-left": "env(safe-area-inset-left, 0px)",
        sidebar: "var(--sidebar-width)",
        header: "var(--header-height)",
        "nav-rail": "var(--nav-rail-width)",
      },
      transitionDuration: {
        instant: "var(--duration-instant)",
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
      },
      transitionTimingFunction: {
        DEFAULT: "var(--ease-default)",
        default: "var(--ease-default)",
        out: "var(--ease-out)",
        spring: "var(--ease-spring)",
        editorial: "var(--ease-editorial)",
      },
      zIndex: {
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        header: "var(--z-header)",
        overlay: "var(--z-overlay)",
        modal: "var(--z-modal)",
        toast: "var(--z-toast)",
        splash: "var(--z-splash)",
      },
      animation: {
        "pulse-slow": "pulse var(--duration-slow) var(--ease-default) infinite",
        "dot-bounce": "dotBounce var(--motion-story) var(--ease-default) infinite",
      },
      keyframes: {
        dotBounce: {
          "0%, 80%, 100%": { transform: "scale(0.6)", opacity: "0.5" },
          "40%": { transform: "scale(1)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};
