/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          950: "var(--brand-950)",
          900: "var(--brand-900)",
          800: "var(--brand-800)",
          700: "var(--brand-700)",
          600: "var(--brand-600)",
          100: "var(--brand-100)",
          50: "var(--brand-50)",
        },
        accent: {
          gold: "var(--accent-gold)",
          "gold-soft": "var(--accent-gold-soft)",
        },
        canvas: "var(--canvas)",
        surface: "var(--surface)",
        "surface-subtle": "var(--surface-subtle)",
        "surface-hover": "var(--surface-hover)",
        "surface-selected": "var(--surface-selected)",
        mcneese: {
          blue: "var(--brand-700)",
          gold: "var(--accent-gold)",
          dark: "var(--brand-900)",
          light: "var(--brand-600)",
        },
        "surface-raised": "var(--color-surface-raised)",
        "surface-sunken": "var(--color-surface-sunken)",
        background: "var(--canvas)",
        "bg-secondary": "var(--surface-subtle)",
        "bg-tertiary": "var(--surface-hover)",
        elevated: "var(--surface)",
        border: "var(--border-default)",
        "border-strong": "var(--border-strong)",
        "border-subtle": "var(--surface-hover)",
        "border-focus": "var(--focus-ring)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "text-muted": "var(--text-muted)",
        "text-disabled": "var(--text-disabled)",
        "primary-subtle": "var(--brand-100)",
        "accent-subtle": "var(--accent-gold-soft)",
        success: "var(--success)",
        "success-soft": "var(--success-soft)",
        warning: "var(--warning)",
        "warning-soft": "var(--warning-soft)",
        error: "var(--danger)",
        "danger-soft": "var(--danger-soft)",
        focus: "var(--focus-ring)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        serif: ["var(--font-serif)"],
        mono: ["var(--font-mono)"],
      },
      fontSize: {
        xs: ["var(--text-xs)", { lineHeight: "var(--leading-normal)" }],
        sm: ["var(--text-sm)", { lineHeight: "var(--leading-normal)" }],
        base: ["var(--text-base)", { lineHeight: "var(--leading-normal)" }],
        lg: ["var(--text-lg)", { lineHeight: "var(--leading-snug)" }],
        xl: ["var(--text-xl)", { lineHeight: "var(--leading-snug)" }],
        "2xl": ["var(--text-2xl)", { lineHeight: "var(--leading-tight)" }],
        "3xl": ["var(--text-3xl)", { lineHeight: "var(--leading-tight)" }],
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        soft: "var(--shadow-sm)",
        card: "var(--shadow-md)",
        float: "var(--shadow-lg)",
        focus: "var(--shadow-focus)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        bubble: "18px",
        "bubble-tail": "4px",
      },
      height: {
        header: "var(--header-height)",
        "screen-safe": "100dvh",
      },
      minHeight: {
        composer: "var(--composer-min-height)",
      },
      width: {
        sidebar: "var(--sidebar-width)",
        "sidebar-collapsed": "var(--sidebar-collapsed-width)",
        "nav-rail": "var(--nav-rail-width)",
      },
      maxWidth: {
        chat: "var(--chat-max-width)",
        message: "var(--message-max-width)",
      },
      spacing: {
        safe: "env(safe-area-inset-bottom, 0px)",
        sidebar: "var(--sidebar-width)",
        header: "var(--header-height)",
        "nav-rail": "var(--nav-rail-width)",
      },
      transitionDuration: {
        instant: "var(--duration-instant)",
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
      },
      zIndex: {
        dropdown: "var(--z-dropdown)",
        sticky: "var(--z-sticky)",
        header: "var(--z-header)",
        overlay: "var(--z-overlay)",
        modal: "var(--z-modal)",
        toast: "var(--z-toast)",
        splash: "var(--z-splash)",
      },
      animation: {
        "pulse-slow": "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "dot-bounce": "dotBounce 1.4s ease-in-out infinite",
      },
      keyframes: {
        dotBounce: {
          "0%, 80%, 100%": { transform: "scale(0.6)", opacity: "0.5" },
          "40%": { transform: "scale(1)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
};
